/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder Books */
        patch: operations["reorder_books_api_projects__project_id__order_patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Book */
        post: operations["upload_book_api_projects__project_id__books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_api_books__book_id__get"];
        put?: never;
        post?: never;
        /** Delete Book */
        delete: operations["delete_book_api_books__book_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book Status */
        get: operations["get_book_status_api_books__book_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Book */
        post: operations["reprocess_book_api_books__book_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chapters */
        get: operations["list_chapters_api_books__book_id__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["list_chunks_api_books__book_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/pages/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Render Page */
        get: operations["render_page_api_books__book_id__pages__page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_api_projects__project_id__characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character_api_characters__character_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mentions */
        get: operations["list_mentions_api_characters__character_id__mentions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/appearances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Appearances */
        get: operations["list_appearances_api_characters__character_id__appearances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Characters */
        post: operations["merge_characters_api_characters_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Split Character */
        post: operations["split_character_api_characters__character_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/ontology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ontology */
        get: operations["get_ontology_api_graph_ontology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_projects__project_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/neighbourhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Neighbourhood */
        get: operations["get_neighbourhood_api_characters__character_id__neighbourhood_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations/{relation_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_relations__relation_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations/arc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Arc */
        get: operations["get_arc_api_relations_arc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Path */
        get: operations["get_path_api_graph_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Server-sent events. Each frame is one QueryEvent, discriminated on `type`: token, citation, route, interrupt, done, error.
         */
        post: operations["ask_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/{thread_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond To Clarification */
        post: operations["respond_to_clarification_api_query__thread_id__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_review_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/tasks/{task_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Task */
        post: operations["resolve_task_api_review_tasks__task_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus per-dependency status.
         *
         *     Implemented shallow at the freeze so compose has something to gate on;
         *     do1 fills in the real dependency probes in S1.12.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_ops_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/pipeline/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pipeline Runs */
        get: operations["pipeline_runs_api_ops_pipeline_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/pipeline/dead-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dead Letter */
        get: operations["dead_letter_api_ops_pipeline_dead_letter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/routing-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Routing Policy */
        get: operations["get_routing_policy_api_ops_routing_policy_get"];
        /** Set Routing Policy */
        put: operations["set_routing_policy_api_ops_routing_policy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Root-level alias so container healthchecks do not depend on the API prefix.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasOut */
        AliasOut: {
            /** Surface Form */
            surface_form: string;
            /** Count */
            count: number;
            resolution_method: components["schemas"]["ResolutionMethod"];
            /**
             * Ambiguous
             * @default false
             */
            ambiguous: boolean;
        };
        /** AppearanceOut */
        AppearanceOut: {
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Series Order */
            series_order?: number | null;
            /** Book Title */
            book_title: string;
            /** First Page */
            first_page?: number | null;
            /** First Chapter */
            first_chapter?: number | null;
            /**
             * Mention Count
             * @default 0
             */
            mention_count: number;
            importance_tier: components["schemas"]["ImportanceTier"];
            /** Surface Forms */
            surface_forms?: string[];
        };
        /**
         * AssertionType
         * @description How a relationship is known. ``DIALOGUE`` is not the same as fact.
         * @enum {string}
         */
        AssertionType: "narrated" | "dialogue" | "inferred";
        /** AttributeOut */
        AttributeOut: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Book Id */
            book_id?: string | null;
            /** Page */
            page: number;
        };
        /** Body_upload_book_api_projects__project_id__books_post */
        Body_upload_book_api_projects__project_id__books_post: {
            /** File */
            file: string;
        };
        /**
         * BookOrderUpdate
         * @description Reordering recomputes derived character fields; it does not re-extract.
         */
        BookOrderUpdate: {
            /** Order */
            order: string[];
        };
        /** BookOut */
        BookOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Series Order */
            series_order?: number | null;
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** Chapter Count */
            chapter_count?: number | null;
            /**
             * Character Count
             * @default 0
             */
            character_count: number;
            status: components["schemas"]["BookStatus"];
            /** Ingested At */
            ingested_at?: string | null;
        };
        /**
         * BookStatus
         * @enum {string}
         */
        BookStatus: "queued" | "processing" | "ready" | "failed";
        /** BookStatusOut */
        BookStatusOut: {
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            status: components["schemas"]["BookStatus"];
            /** Stages */
            stages?: components["schemas"]["StageStatus"][];
            /** Estimated Seconds Remaining */
            estimated_seconds_remaining?: number | null;
            /** Trace Url */
            trace_url?: string | null;
        };
        /** ChapterOut */
        ChapterOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Number */
            number?: number | null;
            /** Title */
            title?: string | null;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            detection_method: components["schemas"]["DetectionMethod"];
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
        };
        /** CharacterDetailOut */
        CharacterDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Aliases */
            aliases?: string[];
            importance_tier: components["schemas"]["ImportanceTier"];
            /**
             * Mention Count
             * @default 0
             */
            mention_count: number;
            /** First Page */
            first_page?: number | null;
            /** First Chapter */
            first_chapter?: number | null;
            /** First Book Id */
            first_book_id?: string | null;
            /** Appears In Books */
            appears_in_books?: number[];
            /**
             * Collision Suspected
             * @default false
             */
            collision_suspected: boolean;
            /**
             * Human Verified
             * @default false
             */
            human_verified: boolean;
            /** Alias Detail */
            alias_detail?: components["schemas"]["AliasOut"][];
            /** Attributes */
            attributes?: components["schemas"]["AttributeOut"][];
            /** Appearances */
            appearances?: components["schemas"]["AppearanceOut"][];
            /** Mentions Per Chapter */
            mentions_per_chapter?: {
                [key: string]: number;
            };
        };
        /** CharacterMergeRequest */
        CharacterMergeRequest: {
            /** Source Ids */
            source_ids: string[];
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Canonical Name */
            canonical_name?: string | null;
        };
        /** CharacterOut */
        CharacterOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Aliases */
            aliases?: string[];
            importance_tier: components["schemas"]["ImportanceTier"];
            /**
             * Mention Count
             * @default 0
             */
            mention_count: number;
            /** First Page */
            first_page?: number | null;
            /** First Chapter */
            first_chapter?: number | null;
            /** First Book Id */
            first_book_id?: string | null;
            /** Appears In Books */
            appears_in_books?: number[];
            /**
             * Collision Suspected
             * @default false
             */
            collision_suspected: boolean;
            /**
             * Human Verified
             * @default false
             */
            human_verified: boolean;
        };
        /** CharacterSplitRequest */
        CharacterSplitRequest: {
            /** Mention Ids */
            mention_ids: string[];
            /** New Canonical Name */
            new_canonical_name: string;
        };
        /** ChunkOut */
        ChunkOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Chapter Id */
            chapter_id?: string | null;
            /** Chapter Number */
            chapter_number?: number | null;
            /** Text */
            text: string;
            /** Pages */
            pages: number[];
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Token Count */
            token_count?: number | null;
            /** Dense Score */
            dense_score?: number | null;
            /** Lexical Score */
            lexical_score?: number | null;
        };
        /** CitationEvent */
        CitationEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "citation";
            /** Index */
            index: number;
            citation: components["schemas"]["CitationOut"];
        };
        /** CitationOut */
        CitationOut: {
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Book Title */
            book_title?: string | null;
            /** Series Order */
            series_order?: number | null;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Chapter No */
            chapter_no?: number | null;
            /** Quote */
            quote?: string | null;
            /** Chunk Id */
            chunk_id?: string | null;
        };
        /** ClarifyResponse */
        ClarifyResponse: {
            /** Answer */
            answer: string;
        };
        /** DeadLetterOut */
        DeadLetterOut: {
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Book Title */
            book_title: string;
            /** Stage */
            stage: string;
            /** Error Class */
            error_class?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Trace Url */
            trace_url?: string | null;
        };
        /** DependencyHealth */
        DependencyHealth: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /**
         * DetectionMethod
         * @enum {string}
         */
        DetectionMethod: "regex" | "llm" | "manual";
        /** DoneEvent */
        DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /**
             * Citation Count
             * @default 0
             */
            citation_count: number;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Message */
            message: string;
            /**
             * Recoverable
             * @default false
             */
            recoverable: boolean;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Book Title */
            book_title?: string | null;
            /** Series Order */
            series_order?: number | null;
            /** Chapter No */
            chapter_no?: number | null;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Quote */
            quote: string;
            assertion_type: components["schemas"]["AssertionType"];
            /** Asserted By */
            asserted_by?: string | null;
            /** Confidence */
            confidence?: number | null;
        };
        /** GraphEdgeOut */
        GraphEdgeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source
             * Format: uuid
             */
            source: string;
            /**
             * Target
             * Format: uuid
             */
            target: string;
            /** Predicate */
            predicate: string;
            family: components["schemas"]["RelationFamily"];
            /** Confidence */
            confidence: number;
            /** Evidence Count */
            evidence_count: number;
            /**
             * Hearsay
             * @default false
             */
            hearsay: boolean;
            /** Page Refs */
            page_refs?: number[];
        };
        /** GraphNodeOut */
        GraphNodeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Name */
            canonical_name: string;
            importance_tier: components["schemas"]["ImportanceTier"];
            /**
             * Mention Count
             * @default 0
             */
            mention_count: number;
            /** First Book Order */
            first_book_order?: number | null;
            /** First Chapter */
            first_chapter?: number | null;
            /** Appears In Books */
            appears_in_books?: number[];
        };
        /** GraphOut */
        GraphOut: {
            /** Nodes */
            nodes?: components["schemas"]["GraphNodeOut"][];
            /** Edges */
            edges?: components["schemas"]["GraphEdgeOut"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** GraphPathOut */
        GraphPathOut: {
            /** Hops */
            hops?: components["schemas"]["RelationOut"][];
            /**
             * Found
             * @default true
             */
            found: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Dependencies */
            dependencies?: components["schemas"]["DependencyHealth"][];
        };
        /**
         * ImportanceTier
         * @enum {string}
         */
        ImportanceTier: "protagonist" | "major" | "minor" | "mentioned";
        /** IngestionRunOut */
        IngestionRunOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Stages */
            stages: components["schemas"]["StageStatus"][];
            /** Trace Url */
            trace_url?: string | null;
        };
        /** InterruptEvent */
        InterruptEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "interrupt";
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Question */
            question: string;
            /** Options */
            options?: string[];
        };
        /** MentionOut */
        MentionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Surface Form */
            surface_form: string;
            /** Page */
            page: number;
            /** Context */
            context?: string | null;
            resolution_method: components["schemas"]["ResolutionMethod"];
        };
        /** MetricsOut */
        MetricsOut: {
            /** Book Id */
            book_id?: string | null;
            /** Stages */
            stages?: components["schemas"]["StageCost"][];
            /**
             * Total Cost Usd
             * @default 0
             */
            total_cost_usd: number;
            /** Prefix Cache Hit Rate */
            prefix_cache_hit_rate?: number | null;
        };
        /** OntologyOut */
        OntologyOut: {
            /** Predicates */
            predicates?: components["schemas"]["OntologyPredicateOut"][];
            /** Families */
            families?: components["schemas"]["RelationFamily"][];
        };
        /** OntologyPredicateOut */
        OntologyPredicateOut: {
            /** Predicate */
            predicate: string;
            family: components["schemas"]["RelationFamily"];
            /** Inverse */
            inverse?: string | null;
            /**
             * Symmetric
             * @default false
             */
            symmetric: boolean;
        };
        /** PageRenderOut */
        PageRenderOut: {
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Page */
            page: number;
            /** Image Url */
            image_url: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Spans */
            spans?: components["schemas"]["SpanBox"][];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** @default standalone */
            kind: components["schemas"]["ProjectKind"];
        };
        /** ProjectDetailOut */
        ProjectDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            kind: components["schemas"]["ProjectKind"];
            /**
             * Book Count
             * @default 0
             */
            book_count: number;
            /**
             * Character Count
             * @default 0
             */
            character_count: number;
            /**
             * Relation Count
             * @default 0
             */
            relation_count: number;
            /** Updated At */
            updated_at?: string | null;
            /** Books */
            books?: components["schemas"]["BookOut"][];
        };
        /**
         * ProjectKind
         * @enum {string}
         */
        ProjectKind: "standalone" | "series";
        /** ProjectOut */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            kind: components["schemas"]["ProjectKind"];
            /**
             * Book Count
             * @default 0
             */
            book_count: number;
            /**
             * Character Count
             * @default 0
             */
            character_count: number;
            /**
             * Relation Count
             * @default 0
             */
            relation_count: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * QueryEventEnvelope
         * @description Documents the SSE stream for the generated client.
         *
         *     The wire format is ``text/event-stream``; this envelope exists so the
         *     generated TypeScript carries the discriminated union.
         */
        QueryEventEnvelope: {
            /** Event */
            event: components["schemas"]["TokenEvent"] | components["schemas"]["CitationEvent"] | components["schemas"]["RouteEvent"] | components["schemas"]["InterruptEvent"] | components["schemas"]["DoneEvent"] | components["schemas"]["ErrorEvent"];
        };
        /** QueryRequest */
        QueryRequest: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Question */
            question: string;
            /** Thread Id */
            thread_id?: string | null;
            /** Limit Book Order */
            limit_book_order?: number | null;
            /** Limit Chapter */
            limit_chapter?: number | null;
        };
        /**
         * QueryRoute
         * @enum {string}
         */
        QueryRoute: "character_lookup" | "relationship_lookup" | "path" | "aggregation" | "series_arc" | "narrative" | "ambiguous";
        /**
         * RelationArcOut
         * @description The ordered sequence of states for one pair.
         *
         *     A relationship that never changes is a one-element sequence, so callers
         *     have a single code path.
         */
        RelationArcOut: {
            /**
             * Subject Character Id
             * Format: uuid
             */
            subject_character_id: string;
            /**
             * Object Character Id
             * Format: uuid
             */
            object_character_id: string;
            /** States */
            states?: components["schemas"]["RelationOut"][];
        };
        /**
         * RelationFamily
         * @enum {string}
         */
        RelationFamily: "kinship" | "romantic" | "social" | "adversarial" | "structural";
        /** RelationOut */
        RelationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Subject Character Id
             * Format: uuid
             */
            subject_character_id: string;
            /** Subject Name */
            subject_name: string;
            /** Predicate */
            predicate: string;
            /**
             * Object Character Id
             * Format: uuid
             */
            object_character_id: string;
            /** Object Name */
            object_name: string;
            family: components["schemas"]["RelationFamily"];
            /** Confidence */
            confidence: number;
            status: components["schemas"]["RelationStatus"];
            assertion_type: components["schemas"]["AssertionType"];
            /**
             * Hearsay
             * @default false
             */
            hearsay: boolean;
            /**
             * Evidence Count
             * @default 0
             */
            evidence_count: number;
            /**
             * First Book Order
             * @default 1
             */
            first_book_order: number;
            /** First Chapter */
            first_chapter?: number | null;
            /** Last Book Order */
            last_book_order?: number | null;
            /** Last Chapter */
            last_chapter?: number | null;
            /** Page Refs */
            page_refs?: number[];
        };
        /**
         * RelationStatus
         * @enum {string}
         */
        RelationStatus: "active" | "ended" | "superseded";
        /**
         * ResolutionMethod
         * @description How a mention ended up in its cluster, or a book roster in a project one.
         * @enum {string}
         */
        ResolutionMethod: "exact" | "normalised" | "honorific" | "nickname" | "embedding" | "llm" | "human";
        /** ReviewResolution */
        ReviewResolution: {
            /** Decision */
            decision: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "open" | "resolved" | "dismissed";
        /** ReviewTaskOut */
        ReviewTaskOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Book Id */
            book_id?: string | null;
            task_type: components["schemas"]["ReviewTaskType"];
            status: components["schemas"]["ReviewStatus"];
            /** Priority */
            priority: number;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReviewTaskType
         * @enum {string}
         */
        ReviewTaskType: "merge_characters" | "merge_across_books" | "confirm_relation" | "resolve_conflict" | "classify_candidate" | "confirm_chapter_split";
        /** RouteEvent */
        RouteEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "route";
            route: components["schemas"]["QueryRoute"];
            /** Explanation */
            explanation?: string | null;
            /** Retrieval Tier */
            retrieval_tier?: string | null;
        };
        /** RoutingPolicyOut */
        RoutingPolicyOut: {
            /** Version */
            version: number;
            /** Purposes */
            purposes?: {
                [key: string]: string;
            };
        };
        /** SearchResultOut */
        SearchResultOut: {
            /** Chunks */
            chunks?: components["schemas"]["ChunkOut"][];
            /** Tier */
            tier?: string | null;
        };
        /**
         * SpanBox
         * @description PDF user space, origin top-left, unscaled. Agreed with the frontend once.
         */
        SpanBox: {
            /** Page */
            page: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** StageCost */
        StageCost: {
            /** Stage */
            stage: string;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
        };
        /**
         * StageName
         * @description The frozen ingestion stages. These strings are also the Celery task names.
         *
         *     Changing one renames a Celery task and orphans anything already queued.
         * @enum {string}
         */
        StageName: "pipeline.parse_and_chunk" | "pipeline.segment_chapters" | "pipeline.embed_chunks" | "pipeline.extract_characters" | "pipeline.resolve_aliases" | "pipeline.reconcile_characters" | "relations.extract" | "relations.aggregate" | "graph.upsert";
        /**
         * StageState
         * @enum {string}
         */
        StageState: "pending" | "running" | "succeeded" | "failed" | "skipped";
        /** StageStatus */
        StageStatus: {
            stage: components["schemas"]["StageName"];
            state: components["schemas"]["StageState"];
            /**
             * Attempt
             * @default 0
             */
            attempt: number;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /** TokenEvent */
        TokenEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "token";
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_books_api_projects__project_id__order_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookOrderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_book_api_projects__project_id__books_post: {
        parameters: {
            query?: {
                series_order?: number | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_book_api_projects__project_id__books_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_api_books__book_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_status_api_books__book_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_book_api_books__book_id__reprocess_post: {
        parameters: {
            query?: {
                from_stage?: string | null;
            };
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chapters_api_books__book_id__chapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_api_books__book_id__chunks_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_page_api_books__book_id__pages__page__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageRenderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_characters_api_projects__project_id__characters_get: {
        parameters: {
            query?: {
                tier?: components["schemas"]["ImportanceTier"] | null;
                /** @description Alias-aware search */
                q?: string | null;
                book_id?: string | null;
                limit_book_order?: number | null;
                limit_chapter?: number | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_api_characters__character_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mentions_api_characters__character_id__mentions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                limit_chapter?: number | null;
            };
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_appearances_api_characters__character_id__appearances_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppearanceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_characters_api_characters_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterMergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_character_api_characters__character_id__split_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterSplitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ontology_api_graph_ontology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OntologyOut"];
                };
            };
        };
    };
    get_graph_api_projects__project_id__graph_get: {
        parameters: {
            query?: {
                /** @description A slice of the standing graph */
                book_id?: string | null;
                families?: components["schemas"]["RelationFamily"][] | null;
                min_confidence?: number;
                limit_book_order?: number | null;
                limit_chapter?: number | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neighbourhood_api_characters__character_id__neighbourhood_get: {
        parameters: {
            query?: {
                depth?: number;
            };
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_relations__relation_id__evidence_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_arc_api_relations_arc_get: {
        parameters: {
            query: {
                a: string;
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationArcOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_path_api_graph_path_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                max_hops?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPathOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryEventEnvelope"];
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_to_clarification_api_query__thread_id__respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClarifyResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryEventEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                project_id: string;
                q: string;
                book_id?: string | null;
                limit?: number;
                limit_book_order?: number | null;
                limit_chapter?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_review_tasks_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                task_type?: components["schemas"]["ReviewTaskType"] | null;
                status?: components["schemas"]["ReviewStatus"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_task_api_review_tasks__task_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewResolution"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    metrics_api_ops_metrics_get: {
        parameters: {
            query?: {
                book_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_runs_api_ops_pipeline_runs_get: {
        parameters: {
            query?: {
                book_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dead_letter_api_ops_pipeline_dead_letter_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeadLetterOut"][];
                };
            };
        };
    };
    get_routing_policy_api_ops_routing_policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingPolicyOut"];
                };
            };
        };
    };
    set_routing_policy_api_ops_routing_policy_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingPolicyOut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingPolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
