"""document_chunks

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-01 19:09:24.150736

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401 (used by generated column types, e.g. sqlmodel.sql.sqltypes.AutoString)
from alembic import op
from pgvector.sqlalchemy.vector import VECTOR

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documentchunk",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("text_embedding", VECTOR(dim=1024), nullable=True),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("headings", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pages", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("document", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documentchunk")
    # ### end Alembic commands ###
