"""optional uploaded_by

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-01 19:40:49.732787

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401 (used by generated column types, e.g. sqlmodel.sql.sqltypes.AutoString)
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "uploaded_by", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "documentchunk",
        "headings",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.drop_column("documentchunk", "embed_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documentchunk",
        sa.Column("embed_text", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "documentchunk",
        "headings",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    op.alter_column("document", "uploaded_by", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
