"""v2 schema: projects, series, characters, relations, evidence

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-17 12:10:43.450425

"""
from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 (used by generated column types, e.g. sqlmodel.sql.sqltypes.AutoString)
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: str | Sequence[str] | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # v1 chunks hang off `document`, which this migration removes, and there is
    # no book to re-point them at. They are prototype output and are recreated by
    # re-ingesting the source PDF.
    op.execute("TRUNCATE TABLE documentchunk")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evalrun',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corpus_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('git_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('STANDALONE', 'SERIES', name='projectkind'), nullable=False),
    sa.Column('roster_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_slug'), 'project', ['slug'], unique=True)
    op.create_table('book',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('series_order', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'READY', 'FAILED', name='bookstatus'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'series_order', name='uq_book_project_order')
    )
    op.create_index(op.f('ix_book_content_hash'), 'book', ['content_hash'], unique=True)
    op.create_index('ix_book_project', 'book', ['project_id'], unique=False)
    op.create_table('querylog',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route', sa.Enum('CHARACTER_LOOKUP', 'RELATIONSHIP_LOOKUP', 'PATH', 'AGGREGATION', 'SERIES_ARC', 'NARRATIVE', 'AMBIGUOUS', name='queryroute'), nullable=True),
    sa.Column('cypher_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retrieved_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limit_book_order', sa.Integer(), nullable=True),
    sa.Column('limit_chapter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_querylog_project', 'querylog', ['project_id'], unique=False)
    op.create_table('chapter',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('heading_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('detection_method', sa.Enum('REGEX', 'LLM', 'MANUAL', name='detectionmethod'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'number', name='uq_chapter_book_number')
    )
    op.create_index('ix_chapter_book', 'chapter', ['book_id'], unique=False)
    op.create_table('character',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('importance_tier', sa.Enum('PROTAGONIST', 'MAJOR', 'MINOR', 'MENTIONED', name='importancetier'), nullable=False),
    sa.Column('first_book_id', sa.Uuid(), nullable=True),
    sa.Column('first_chapter', sa.Integer(), nullable=True),
    sa.Column('first_page', sa.Integer(), nullable=True),
    sa.Column('last_book_id', sa.Uuid(), nullable=True),
    sa.Column('last_chapter', sa.Integer(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collision_suspected', sa.Boolean(), nullable=False),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.Column('graph_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['first_book_id'], ['book.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_book_id'], ['book.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'canonical_name', name='uq_character_project_name')
    )
    op.create_index('ix_character_aliases', 'character', ['aliases'], unique=False, postgresql_using='gin')
    op.create_index('ix_character_project', 'character', ['project_id'], unique=False)
    op.create_table('ingestionrun',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('trace_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_book', 'ingestionrun', ['book_id'], unique=False)
    op.create_table('rejectedcandidate',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('surface_form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('PERSON', 'PLACE', 'ORGANISATION', 'UNKNOWN', name='candidatekind'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contexts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rejected_book', 'rejectedcandidate', ['book_id'], unique=False)
    op.create_table('reviewtask',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.Enum('MERGE_CHARACTERS', 'MERGE_ACROSS_BOOKS', 'CONFIRM_RELATION', 'RESOLVE_CONFLICT', 'CLASSIFY_CANDIDATE', 'CONFIRM_CHAPTER_SPLIT', name='reviewtasktype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('graph_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='reviewstatus'), nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_project', 'reviewtask', ['project_id'], unique=False)
    op.create_index('ix_review_status_priority', 'reviewtask', ['status', 'priority'], unique=False)
    op.create_index('ix_review_thread', 'reviewtask', ['graph_thread_id'], unique=False)
    op.create_table('bookcharactercandidate',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('surface_form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cluster_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sa.Enum('PERSON', 'PLACE', 'ORGANISATION', 'UNKNOWN', name='candidatekind'), nullable=False),
    sa.Column('contexts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('resolved_character_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_character_id'], ['character.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_book', 'bookcharactercandidate', ['book_id'], unique=False)
    op.create_table('characterappearance',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('first_page', sa.Integer(), nullable=True),
    sa.Column('first_chapter', sa.Integer(), nullable=True),
    sa.Column('last_page', sa.Integer(), nullable=True),
    sa.Column('last_chapter', sa.Integer(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('importance_tier', sa.Enum('PROTAGONIST', 'MAJOR', 'MINOR', 'MENTIONED', name='importancetier'), nullable=False),
    sa.Column('surface_forms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'book_id', name='uq_appearance_character_book')
    )
    op.create_index('ix_appearance_book', 'characterappearance', ['book_id'], unique=False)
    op.create_table('correctionfeedback',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('review_task_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.Enum('MERGE_CHARACTERS', 'MERGE_ACROSS_BOOKS', 'CONFIRM_RELATION', 'RESOLVE_CONFLICT', 'CLASSIFY_CANDIDATE', 'CONFIRM_CHAPTER_SPLIT', name='reviewtasktype'), nullable=False),
    sa.Column('model_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('resolution_method', sa.Enum('EXACT', 'NORMALISED', 'HONORIFIC', 'NICKNAME', 'EMBEDDING', 'LLM', 'HUMAN', name='resolutionmethod'), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_task_id'], ['reviewtask.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_task_type', 'correctionfeedback', ['task_type'], unique=False)
    op.create_table('ingestionstage',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('PARSE_AND_CHUNK', 'SEGMENT_CHAPTERS', 'EMBED_CHUNKS', 'EXTRACT_CHARACTERS', 'RESOLVE_ALIASES', 'RECONCILE_CHARACTERS', 'EXTRACT_RELATIONS', 'AGGREGATE_RELATIONS', 'UPSERT_GRAPH', name='stagename'), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='stagestate'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('error_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('traceback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestionrun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'stage', name='uq_stage_run_stage')
    )
    op.create_index('ix_stage_state', 'ingestionstage', ['state'], unique=False)
    op.create_table('relation',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('subject_character_id', sa.Uuid(), nullable=False),
    sa.Column('object_character_id', sa.Uuid(), nullable=False),
    sa.Column('predicate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family', sa.Enum('KINSHIP', 'ROMANTIC', 'SOCIAL', 'ADVERSARIAL', 'STRUCTURAL', name='relationfamily'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'SUPERSEDED', name='relationstatus'), nullable=False),
    sa.Column('assertion_type', sa.Enum('NARRATED', 'DIALOGUE', 'INFERRED', name='assertiontype'), nullable=False),
    sa.Column('asserted_by_character_id', sa.Uuid(), nullable=True),
    sa.Column('hearsay', sa.Boolean(), nullable=False),
    sa.Column('first_book_order', sa.Integer(), nullable=False),
    sa.Column('first_chapter', sa.Integer(), nullable=True),
    sa.Column('last_book_order', sa.Integer(), nullable=True),
    sa.Column('last_chapter', sa.Integer(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.Column('graph_edge_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('subject_character_id <> object_character_id', name='ck_relation_no_self'),
    sa.ForeignKeyConstraint(['asserted_by_character_id'], ['character.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_character_id'], ['character.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_character_id', 'predicate', 'object_character_id', 'first_book_order', 'first_chapter', name='uq_relation_aggregation_key')
    )
    op.create_index('ix_relation_object', 'relation', ['object_character_id'], unique=False)
    op.create_index('ix_relation_position', 'relation', ['project_id', 'first_book_order', 'first_chapter'], unique=False)
    op.create_index('ix_relation_project_predicate', 'relation', ['project_id', 'predicate'], unique=False)
    op.create_index('ix_relation_subject', 'relation', ['subject_character_id'], unique=False)
    op.create_table('charactermention',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('surface_form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolution_method', sa.Enum('EXACT', 'NORMALISED', 'HONORIFIC', 'NICKNAME', 'EMBEDDING', 'LLM', 'HUMAN', name='resolutionmethod'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['documentchunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mention_book', 'charactermention', ['book_id'], unique=False)
    op.create_index('ix_mention_character', 'charactermention', ['character_id'], unique=False)
    op.create_index('ix_mention_chunk', 'charactermention', ['chunk_id'], unique=False)
    op.create_table('relationevidence',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('book_order', sa.Integer(), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assertion_type', sa.Enum('NARRATED', 'DIALOGUE', 'INFERRED', name='assertiontype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.CheckConstraint('length(quote) <= 400', name='ck_evidence_quote_len'),
    sa.CheckConstraint('page_start >= 1 AND page_end >= page_start', name='ck_evidence_pages'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['documentchunk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_id'], ['relation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_book', 'relationevidence', ['book_id'], unique=False)
    op.create_index('ix_evidence_relation', 'relationevidence', ['relation_id'], unique=False)
    op.add_column('documentchunk', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documentchunk', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documentchunk', sa.Column('book_id', sa.Uuid(), nullable=False))
    op.add_column('documentchunk', sa.Column('chapter_id', sa.Uuid(), nullable=True))
    op.add_column('documentchunk', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('documentchunk', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True))
    op.alter_column('documentchunk', 'pages',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    op.create_index('ix_chunk_book', 'documentchunk', ['book_id'], unique=False)
    op.create_index('ix_chunk_chapter', 'documentchunk', ['chapter_id'], unique=False)
    op.create_index('ix_chunk_tsv', 'documentchunk', ['tsv'], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('documentchunk_document_fkey'), 'documentchunk', type_='foreignkey')
    # Named explicitly: an anonymous constraint cannot be dropped on downgrade.
    op.create_foreign_key('fk_chunk_chapter', 'documentchunk', 'chapter', ['chapter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_chunk_book', 'documentchunk', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('ck_chunk_pages', 'documentchunk', 'page_start >= 1 AND page_end >= page_start')
    op.drop_column('documentchunk', 'document_id')
    # Dropped last: documentchunk's foreign key referenced it until the line above.
    op.drop_table('document')
    op.create_index(
        "ix_chunk_embedding_hnsw",
        "documentchunk",
        ["text_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"text_embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Structure only: this migration truncates v1 chunks and drops `document`,
    # so rolling back cannot restore their contents.
    # `document` is recreated first — documentchunk's foreign key needs it.
    op.create_table('document',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('document_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_pkey'))
    )

    op.drop_index(
        "ix_chunk_embedding_hnsw",
        table_name="documentchunk",
        postgresql_using="hnsw",
        postgresql_ops={"text_embedding": "vector_cosine_ops"},
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentchunk', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('ck_chunk_pages', 'documentchunk', type_='check')
    op.drop_constraint('fk_chunk_book', 'documentchunk', type_='foreignkey')
    op.drop_constraint('fk_chunk_chapter', 'documentchunk', type_='foreignkey')
    op.create_foreign_key(op.f('documentchunk_document_fkey'), 'documentchunk', 'document', ['document_id'], ['id'])
    op.drop_index('ix_chunk_tsv', table_name='documentchunk', postgresql_using='gin')
    op.drop_index('ix_chunk_chapter', table_name='documentchunk')
    op.drop_index('ix_chunk_book', table_name='documentchunk')
    op.alter_column('documentchunk', 'pages',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    op.drop_column('documentchunk', 'tsv')
    op.drop_column('documentchunk', 'token_count')
    op.drop_column('documentchunk', 'chapter_id')
    op.drop_column('documentchunk', 'book_id')
    op.drop_column('documentchunk', 'updated_at')
    op.drop_column('documentchunk', 'created_at')
    op.drop_index('ix_evidence_relation', table_name='relationevidence')
    op.drop_index('ix_evidence_book', table_name='relationevidence')
    op.drop_table('relationevidence')
    op.drop_index('ix_mention_chunk', table_name='charactermention')
    op.drop_index('ix_mention_character', table_name='charactermention')
    op.drop_index('ix_mention_book', table_name='charactermention')
    op.drop_table('charactermention')
    op.drop_index('ix_relation_subject', table_name='relation')
    op.drop_index('ix_relation_project_predicate', table_name='relation')
    op.drop_index('ix_relation_position', table_name='relation')
    op.drop_index('ix_relation_object', table_name='relation')
    op.drop_table('relation')
    op.drop_index('ix_stage_state', table_name='ingestionstage')
    op.drop_table('ingestionstage')
    op.drop_index('ix_feedback_task_type', table_name='correctionfeedback')
    op.drop_table('correctionfeedback')
    op.drop_index('ix_appearance_book', table_name='characterappearance')
    op.drop_table('characterappearance')
    op.drop_index('ix_candidate_book', table_name='bookcharactercandidate')
    op.drop_table('bookcharactercandidate')
    op.drop_index('ix_review_thread', table_name='reviewtask')
    op.drop_index('ix_review_status_priority', table_name='reviewtask')
    op.drop_index('ix_review_project', table_name='reviewtask')
    op.drop_table('reviewtask')
    op.drop_index('ix_rejected_book', table_name='rejectedcandidate')
    op.drop_table('rejectedcandidate')
    op.drop_index('ix_run_book', table_name='ingestionrun')
    op.drop_table('ingestionrun')
    op.drop_index('ix_character_project', table_name='character')
    op.drop_index('ix_character_aliases', table_name='character', postgresql_using='gin')
    op.drop_table('character')
    op.drop_index('ix_chapter_book', table_name='chapter')
    op.drop_table('chapter')
    op.drop_index('ix_querylog_project', table_name='querylog')
    op.drop_table('querylog')
    op.drop_index('ix_book_project', table_name='book')
    op.drop_index(op.f('ix_book_content_hash'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_project_slug'), table_name='project')
    op.drop_table('project')
    op.drop_table('evalrun')
    # ### end Alembic commands ###

    # Table drops leave their ENUM types behind, and a later re-upgrade then
    # fails with 'type already exists'. Drop them explicitly.
    for enum_name in (
        "assertiontype",
        "bookstatus",
        "candidatekind",
        "detectionmethod",
        "importancetier",
        "projectkind",
        "queryroute",
        "relationfamily",
        "relationstatus",
        "resolutionmethod",
        "reviewstatus",
        "reviewtasktype",
        "stagename",
        "stagestate",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
