#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

DEFAULT_RUN_PATH = REPO_ROOT / "eval" / "ablation_runs" / "latest.json"
README_PATH = REPO_ROOT / "README.md"

START_MARKER = "<!-- ablation-table:start (auto-generated by scripts/publish_ablation_readme.py, S8.10 -- do not hand-edit) -->"
END_MARKER = "<!-- ablation-table:end -->"

AXIS_TITLES = {
    "extraction": "Extraction (single-pass vs two-pass, string-only vs full alias cascade)",
    "retrieval": "Retrieval (vector-only -> +BM25 -> +rerank -> graph-constrained)",
    "model": "Model (Qwen3-8B local vs frontier API vs routed)",
}
AXIS_ORDER = ["extraction", "retrieval", "model"]


def _fmt(value: float | None) -> str:
    return "—" if value is None else f"{value:.3f}"


def _status_label(cell: dict[str, Any]) -> str:
    return {"measured": "measured", "partial": "partial", "blocked": "blocked"}.get(
        cell["status"], cell["status"]
    )


def render_axis_table(cells: list[dict[str, Any]]) -> str:
    lines = [
        "| Configuration | Book | Precision | Recall | F1 | Accuracy | n | Status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for cell in cells:
        m = cell["metrics"]
        recommended = " **(recommended)**" if cell.get("recommended") else ""
        label = cell["label"].replace(" (recommended)", "") + recommended
        book = cell.get("book_key") or "—"
        lines.append(
            f"| {label} | {book} | {_fmt(m.get('precision'))} | {_fmt(m.get('recall'))} "
            f"| {_fmt(m.get('f1'))} | {_fmt(m.get('accuracy'))} | {m.get('sample_size', 0)} "
            f"| {_status_label(cell)} |"
        )

    return "\n".join(lines)


def render_legend(cells: list[dict[str, Any]]) -> str:
    reasons = {c["blocked_reason"] for c in cells if c.get("blocked_reason")}
    if not reasons:
        return ""

    lines = ["", "<details><summary>Why cells are blocked or partial</summary>", ""]
    for reason in sorted(reasons):
        lines.append(f"- {reason}")
    lines.append("")
    lines.append("</details>")

    return "\n".join(lines)


def render_section(artifact: dict[str, Any]) -> str:
    summary = artifact.get("summary", {})
    git_sha = (artifact.get("git_sha") or "unknown")[:12]
    lines = [
        START_MARKER,
        "",
        "## Eval ablation table",
        "",
        (
            f"Run `{artifact['run_id']}` · generated {artifact['generated_at']} · "
            f"git `{git_sha}` · corpus manifest `{artifact.get('corpus_version') or 'unknown'}`"
        ),
        "",
        (
            f"{summary.get('measured', 0)} measured, {summary.get('partial', 0)} partial, "
            f"{summary.get('blocked', 0)} blocked of {summary.get('total_rows', 0)} rows."
        ),
        "",
        (
            "**This is a partial matrix by design, not the full cross product** -- each row "
            "varies one axis against the recommended value of the other two "
            "(`plans/sprint-8/README.md`); a full extraction x retrieval x model sweep is "
            "30+ full-novel runs and most cells would be uninteresting."
        ),
        "",
    ]

    cells_by_axis: dict[str, list[dict[str, Any]]] = {axis: [] for axis in AXIS_ORDER}
    for cell in artifact.get("cells", []):
        cells_by_axis.setdefault(cell["axis"], []).append(cell)

    for axis in AXIS_ORDER:
        axis_cells = cells_by_axis.get(axis, [])
        if not axis_cells:
            continue
        lines.append(f"### {AXIS_TITLES.get(axis, axis)}")
        lines.append("")
        lines.append(render_axis_table(axis_cells))
        legend = render_legend(axis_cells)
        if legend:
            lines.append(legend)
        lines.append("")

    lines.append(END_MARKER)

    return "\n".join(lines).rstrip() + "\n"


def splice(readme_text: str, section: str) -> str:
    """Replace the marked section, or append it, leaving everything else --
    including exact whitespace outside the markers -- untouched.

    Both branches normalise to exactly one blank line around the section, so
    splicing the same artifact in twice reproduces byte-identical output
    (CI's nightly commit step relies on this: no diff means no commit).
    """
    if START_MARKER in readme_text and END_MARKER in readme_text:
        before, rest = readme_text.split(START_MARKER, 1)
        _, after = rest.split(END_MARKER, 1)
    else:
        before, after = readme_text, ""

    before = before.rstrip("\n")
    after = after.lstrip("\n")

    parts = [p for p in (before, section.rstrip("\n"), after) if p]

    return "\n\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", default=str(DEFAULT_RUN_PATH))
    args = parser.parse_args()

    run_path = Path(args.run)
    if not run_path.exists():
        print(
            f"no ablation run found at {run_path} -- run `make eval-ablation` first. "
            "Leaving README.md untouched.",
            file=sys.stderr,
        )

        return 1

    artifact = json.loads(run_path.read_text())
    section = render_section(artifact)

    readme_text = README_PATH.read_text() if README_PATH.exists() else ""
    updated = splice(readme_text, section)
    README_PATH.write_text(updated)

    print(f"README.md's ablation section refreshed from {run_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
